title: MeshMC
author: Tigermouthbear & Makrennel
#email: example@example.com
description: >-
  Mesh is a cross-version minecraft mod development platform for Forge and Fabric.
  It is compatible with Kotlin out of the box, and contains wide varity of other 
  APIs and standard features.
baseurl: ""
url: "https://meshmc.net"
github_username:  MeshMC

theme: minima

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/about.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
